version: "3.7"

services:
    web:
        container_name: pbl_career_web
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html/
            - ./apache.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - 8000:80
        networks:
            - pbl_career

    database:
        container_name: pbl_career_database
        image: postgres
        ports:
            - 3307:5432
        environment:
            POSTGRES_PASSWORD: secret
        volumes:
            - ./.docker/database:/var/lib/postgresql/data
        networks:
            - pbl_career

networks:
    pbl_career:
      name: pbl_career
